schema_version = "1.0.0"

id = "qq_render"
name = "qq Render"
version = "1.0.0"
tagline = "Generate render compositor nodes from view layers"
maintainer = "Tobias Petruj"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Tobias Petruj"]

tags = ["Render", "Compositing", "Pipeline"]
